


            <div class="span9">
                <div class="leaderboard">

                    <form name ="xx" class="form-horizontal" method="post">
                        <fieldset>
                            <legend>Controls Bootstrap supports</legend>
                            <div class="errors"><?php echo $this->errorMessage ?></b></div>
                           <?php echo $this->form; ?>

    <div class="form-actions">

        <input type="submit" name="submit" value="submit">
    </div>
                        </fieldset>
                        
                    </form>

                    <hr>
                    <footer>
                        <p>&copy; Company 2012</p>
                    </footer>

                </div><!--/.fluid-container-->

            </div> <!-- /container -->

            <!-- Le javascript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="../assets/js/jquery.js"></script>
            <script src="../assets/js/bootstrap-transition.js"></script>
            <script src="../assets/js/bootstrap-alert.js"></script>
            <script src="../assets/js/bootstrap-modal.js"></script>
            <script src="../assets/js/bootstrap-dropdown.js"></script>
            <script src="../assets/js/bootstrap-scrollspy.js"></script>
            <script src="../assets/js/bootstrap-tab.js"></script>
            <script src="../assets/js/bootstrap-tooltip.js"></script>
            <script src="../assets/js/bootstrap-popover.js"></script>
            <script src="../assets/js/bootstrap-button.js"></script>
            <script src="../assets/js/bootstrap-collapse.js"></script>
            <script src="../assets/js/bootstrap-carousel.js"></script>
            <script src="../assets/js/bootstrap-typeahead.js"></script>