
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#"></a>
            <div class="nav-collapse">
                <!--<ul class="nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#about">About</a></li>
                  <li><a href="#contact">Contact</a></li>
                </ul>-->
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                        <li class="nav-header">####</li>
                        <li class="active"><a href="#">HTML 4.01</a></li>
                        <li><a href="#">###</a></li>
                        <li><a href="#">####</a></li>
                        <li><a href="#">#######</a></li>
                        <li><a href="#">T###</a></li>
                        <li><a href="#">#########</a></li>
                        <li class="nav-header">Backend</li>
                        <li><a href="#">###</a></li>
                        <li><a href="#">S##L</a></li>
                        <li><a href="#">####</a></li>
                        <li><a href="#">#####</a></li>
                        <li><a href="#">###</a></li>
                    </ul>
                </div><!--/.well -->
            </div><!--/span-->
            <div class="span9">
                <div class="leaderboard">

                    <form name ="xx" class="form-horizontal" method="post">
                        <fieldset>
                            <legend>Controls Bootstrap supports</legend>
                            <div class="errors"><?php echo $this->errorMessage ?></b></div>
                           <?php echo $this->form; ?>

    <div class="form-actions">

        <input type="submit" name="submit" value="submit">
    </div>
                        </fieldset>
                        
                    </form>

                    <hr>
                    <footer>
                        <p>&copy; Company 2012</p>
                    </footer>

                </div><!--/.fluid-container-->

            </div> <!-- /container -->

            <!-- Le javascript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="../assets/js/jquery.js"></script>
            <script src="../assets/js/bootstrap-transition.js"></script>
            <script src="../assets/js/bootstrap-alert.js"></script>
            <script src="../assets/js/bootstrap-modal.js"></script>
            <script src="../assets/js/bootstrap-dropdown.js"></script>
            <script src="../assets/js/bootstrap-scrollspy.js"></script>
            <script src="../assets/js/bootstrap-tab.js"></script>
            <script src="../assets/js/bootstrap-tooltip.js"></script>
            <script src="../assets/js/bootstrap-popover.js"></script>
            <script src="../assets/js/bootstrap-button.js"></script>
            <script src="../assets/js/bootstrap-collapse.js"></script>
            <script src="../assets/js/bootstrap-carousel.js"></script>
            <script src="../assets/js/bootstrap-typeahead.js"></script>