
<?php 
foreach ($this->element as $_element) {
// Here, you can set styling around your elements etc.
?>
<div class="control-group">
    <label class="control-label" for="input01"><?= $_element->getLabel() ?></label>
    <div class="controls">
      <?php echo $_element;?>
       <?php if ($_element->hasErrors()): ?>
        <div class="help-block">
        <?php echo $_element->formErrors($_element->getMessages()); ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<?php
}
?>

    <div class="form-actions">

        <input type="submit" name="submit" value="submit">
    </div>
        </fieldset>
</form>


