<?php $error = ($this->element->hasErrors()) ? 'error': ''?>
<div class="control-group <?=$error?>">
    <label class="control-label" for="input01"><?= $this->element->getLabel() ?></label>
    
    <div class="controls">
        <input type="text" class="input-xlarge" id="<?php echo $this->element->getId();?>" name="<?= $this->element->getName() ?>" value="<?= $this->element->getValue() ?>">
       <div class="help-block">
          
            <?php if ($this->element->hasErrors()): ?>
        
        <?php echo $this->formErrors($this->element->getMessages()); ?>
       
        <?php else:?>
     
            <?php echo $this->element->getDescription();?>
       <?php endif;?>     
       </div>
    </div>

</div>

